# Generated by Django 2.2.6 on 2019-10-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('profile', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('school', models.TextField()),
                ('years_in_prac', models.CharField(max_length=100)),
                ('years_grad', models.CharField(max_length=10)),
                ('license_state', models.CharField(max_length=100)),
                ('cost_p_sess', models.CharField(max_length=30)),
                ('sliding_scale', models.CharField(max_length=10)),
                ('pay_by', models.TextField()),
                ('accept', models.CharField(max_length=10)),
                ('specialties', models.TextField()),
                ('issues', models.TextField()),
                ('mental_health', models.TextField()),
                ('sexuality', models.CharField(max_length=200)),
                ('ethnicity', models.TextField()),
                ('faith', models.CharField(max_length=100)),
                ('age', models.TextField()),
                ('communities', models.TextField()),
                ('languages', models.TextField()),
                ('therapy_types', models.TextField()),
                ('modality', models.TextField()),
                ('video_skype', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
