# Generated by Django 2.2.6 on 2019-10-31 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allminds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='accept',
            new_name='accepted_insurance_plans',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='cost_p_sess',
            new_name='cost_per_session',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='license_state',
            new_name='license_n_state',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='profile',
            new_name='profile_image_url',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='years_grad',
            new_name='year_graduated',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='years_in_prac',
            new_name='years_in_practice',
        ),
    ]
