# Generated by Django 2.2.6 on 2019-10-31 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allminds', '0002_auto_20191031_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='languages',
            new_name='i_also_speak',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='therapy_types',
            new_name='types_of_therapy',
        ),
    ]
