# Generated by Django 2.2.6 on 2019-10-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allminds', '0005_auto_20191031_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='faith',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='license_n_state',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='sliding_scale',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='years_in_practice',
            field=models.CharField(max_length=200),
        ),
    ]
