# Generated by Django 2.2.6 on 2019-10-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allminds', '0006_auto_20191031_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='accepted_insurance_plans',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='cost_per_session',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='faith',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='license_n_state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_image_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='sexuality',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='sliding_scale',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='year_graduated',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='years_in_practice',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='zip_code',
            field=models.TextField(),
        ),
    ]
