# Generated by Django 2.2.7 on 2019-11-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allminds', '0007_auto_20191031_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.TextField(null=True),
        ),
    ]
