# Generated by Django 2.2.7 on 2019-11-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allminds', '0015_person_cost_per_session_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='years_in_practice_total',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
