# Generated by Django 2.2.7 on 2019-11-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allminds', '0017_auto_20191115_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cost_per_session_max',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='cost_per_session_min',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='years_in_practice_total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
