# Generated by Django 2.2.7 on 2019-11-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allminds', '0018_auto_20191114_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cost_per_session_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='cost_per_session_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='years_in_practice_total',
            field=models.IntegerField(default=0),
        ),
    ]
