# Generated by Django 2.2.7 on 2019-11-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allminds', '0019_auto_20191114_2104'),
        ('allminds', '0018_auto_20191115_1114'),
    ]

    operations = [
    ]
