# Generated by Django 2.2.7 on 2019-12-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allminds', '0021_person_accepting_new_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
