# Generated by Django 2.2.7 on 2019-12-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allminds', '0023_auto_20191203_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
