from django.db import models

class Person(models.Model):
	first_name = models.TextField()
	middle_name = models.TextField()
	last_name = models.TextField()
	phone = models.TextField()
	profile_image_url = models.TextField()
	gender = models.TextField()
	city = models.TextField()
	state = models.TextField()
	zip_code = models.TextField()
	title = models.TextField()
	about = models.TextField()
	school = models.TextField()
	years_in_practice = models.TextField()
	year_graduated = models.TextField()
	license_n_state = models.TextField()
	cost_per_session = models.TextField()
	sliding_scale = models.TextField()
	pay_by = models.TextField()
	accepted_insurance_plans = models.TextField()
	specialties = models.TextField()
	issues = models.TextField()
	mental_health = models.TextField()
	sexuality = models.TextField()
	ethnicity = models.TextField()
	faith = models.TextField()
	age = models.TextField()
	communities = models.TextField()
	i_also_speak = models.TextField()
	types_of_therapy = models.TextField()
	modality = models.TextField()
	video_skype = models.TextField()
	url = models.TextField()
	
	def __str__(self):
		return '{} {}'.format(self.first_name,self.last_name)